repos:
  - repo: https://github.com/python-poetry/poetry
    rev: '1.7.0'
    hooks:
      - id: poetry-check
      - id: poetry-lock
      - id: poetry-export
        # args: ["-f", "requirements.txt", "-o", "requirements.txt", "--with", "docs", "--with", "dev", "--without-hashes"]
        args: ["-f", "requirements.txt", "-o", "requirements.txt", "--with", "dev", "--without-hashes"]

repos:
  - repo: https://github.com/psf/black
    rev: 23.7.0  # You can specify the version you want
    hooks:
      - id: black

  - repo: https://github.com/PyCQA/flake8
    rev: 6.1.0  # You can specify the version you want
    hooks:
      - id: flake8
        args: [--ignore=E741 W503 E203 E501 C901]

  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: "./run-mypy"
        language: system
        types: [python]
        require_serial: true
        verbose: true